# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']
source: .
destination: _site/static

# Site Settings
title: "DevFest Praha 2014"
email: "devfestprague@gmail.com"
description: "DevFest Praha 2014, to je den plný zážitků, technologií, networkingu, přednášek a kódu. Od vývojářů pro vývojáře."
baseurl: ""
url: "http://www.devfest.cz"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-35122860-1"
googleAnalyticsSiteUrl: "www.devfest.cz"

# Organizer Info
organizerName: "GDG Lviv"
organizerAlternateName: "Google Developer Group Lviv"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "lviv@gdg.org.ua"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@gughackaton"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/DevFest_Praha_2014_predstaveni_partnerum.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/machineroom/", text: "MachineRoom"}
 - {permalink: "/businessbuild/", text: "BusinessBuild"}
 - {permalink: "/geekfun/", text: "GeekFun"}

bottomNavigationLinks:
 - {link: "https://docs.google.com/forms/d/1dn2Yomh-ZI15ifqB0beSrwpBvLgr8A_y7ujVdjsIUQ0/viewform", text: "Chci se zdarma registrovat"}
 - {link: "https://docs.google.com/forms/d/1Tylmnz_O8N8h5jmqFQsMLm1cpRzD7krXu8J9qaJb5vQ/viewform", text: "Chci vystoupit na DevFestu"}
rightNavigationButtons:
 - {link: "https://docs.google.com/forms/d/1dn2Yomh-ZI15ifqB0beSrwpBvLgr8A_y7ujVdjsIUQ0/viewform", text: "Chci se zdarma registrovat"}
 - {link: "https://docs.google.com/forms/d/1Tylmnz_O8N8h5jmqFQsMLm1cpRzD7krXu8J9qaJb5vQ/viewform", text: "Chci vystoupit na DevFestu"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "To je den plný <typeout>"
eventDate: "Sobota 22. listopadu 2014"
typeoutTextValues: '"zážitků", "technologií", "networkingu", "přednášek", "kódu"'
typeoutFallback: "zážitků"
heroButtons:
 - {link: "https://docs.google.com/forms/d/1dn2Yomh-ZI15ifqB0beSrwpBvLgr8A_y7ujVdjsIUQ0/viewform", text: "Chci se zdarma registrovat"}
 - {link: "https://docs.google.com/forms/d/1Tylmnz_O8N8h5jmqFQsMLm1cpRzD7krXu8J9qaJb5vQ/viewform", text: "Chci vystoupit na DevFestu"}

# About Block
aboutTitle: "Na co se můžu těšit na DevFestu Praha 2014?"
aboutText: "V prvé řadě na poctivou akci od vývojářů pro vývojáře! Třetí ročník podzimního vývojářského festivalu opět nabíjíme Google technologiemi až k prasknutí. Letos se můžete třást nedočkavostí nejen na zajímavé speakery, ale také na bohatý doprovodný program, hříčky z dílny GUGu, a především na setkání se skvělými lidmi a kamarády z oboru, které jste dlouho neviděli. Jednoduše sem hodláme dostat vše, co si jen lze pod slovy Dev (Developers) a Fest (Festival) představit. Registrace je povinná, ale vstup je úplně zadarmo."
aboutBlock:
 - {title: "Přednášky", image: "conference.jpg", text: "Čeká na vás největší koncentrace Google related obsahu na jednom místě – od mobilního a webového vývoje přes cloud, bezpečnost či open source až po kreativní práci s velkými daty, analytiku a mnoho dalšího. To vše z úst skvělých českých i zahraničních speakerů, ze kterých vám bude padat čelist." }
 - {title: "Workshopy", image: "workshop.jpg", text: "Máme jasný cíl – předat vám mnohem více praktických zkušeností než v předchozích letech. Naší hlavní zbraní budou právě workshopy a profíci, kteří je s námi připravují. Přibalte si proto s sebou i notebooky, ať odcházíte nejenom s plnou hlavou inspirací, ale taky kupou kulervoucích projektů." }
 - {title: "Zážitky", image: "hackathon.jpg", text: "Jak by asi vypadal festival bez pořádné porce zážitků a zábavy? Zkoušeli jsme si to představit a vznikl nám z toho dobrý námět na horor. Takže abychom si uchovali autorská práva a mohli je případně později prodat, vydáme se přesně opačnou cestou. Jak zážitků, tak zábavy bude na DevFestu plno!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "550", specialCharacter: "+", info: "účastníků", detail: "odevšad"}
 - {count: "10", specialCharacter: "+", info: "hodin", detail: "vývojářského nebe"}
 - {count: "20", specialCharacter: "+", info: "speakerů", detail: "z ČR i zahraničí"}
 - {count: "3", specialCharacter: "", info: "paralelní tracky", detail: "plus mnoho dalšího"}

# Latest News Block
latestNewsTitle: "Novinky z příprav"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Můžete se těšit na"
rockstarSpeakersButtonText: "Zobrazit všechny speakery"

sectionsTitle: "Sekce"
sections:
 - {name: "MachineRoom", link: "/machineroom/"}
 - {name: "BusinessBuild", link: "/businessbuild/"}
 - {name: "GeekFun", link: "/geekfun/"}
 - {name: "Women Techmakers", link: "/women-techmakers/"}

# Location Block
locationBlockTitle: "Lokalita"
eventLocationName: "Fakulta stavební ČVUT"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "Thákurova 2077/7"
eventAddressLocality: "Praha 6"
eventAddressLocalityRegion: "Praha"
eventPostalCode: "16000"
eventAddressCountry: "Česká republika"
eventStartTime: "2014-10-25T10:00"
eventDoorTime: "09:00"
eventEndTime: "2014-10-25T20:00"
eventPlaceCoordinates: "50.104245, 14.388024"
mapCenterCoordinates: "50.104245, 14.388024"
mapMobileCenterCoordinates: "50.104245, 14.388024"
eventLocationLink: "http://goo.gl/UvjtAq"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueTitle: "Fakulta stavební ČVUT"
venueFeatures: ["Skvělé přednáškové sály", "Spousta prostoru na doprovodný program", "Kousek od metra Dejvická"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "DevFestCZ"
twitterFeed: "http://feed.voracek.net/searchjson.php?q=%23devfestcz"
#""

# Partners Block
organizersTitle: "Organizuje"
#partnersTitle: "Partners"
partnersC4sponsorsButton: "Stát se partnerem"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Chcete nejnovější DevFest info pohodlně do mailu?"
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: ""
subscribeBtnValue: "Pošli"
subscribeEmailPlaceHolder: "your@email.com"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"

# Footer
socialLinks:
 - {link: "https://plus.google.com/102751345660146384940", icon: "google-plus"}
 - {link: "https://twitter.com/GUGcz", icon: "twitter"}
 - {link: "http://www.facebook.com/pages/GUGcz-Ceska-Google-User-Group/69578781928", icon: "facebook"}

footerBlocks:
 -
  title: "Odkazy"
  links:
   - {link: "http://www.gug.cz", text: "GUG.cz"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Kontakty"
  links:
   - {link: "mailto:devfestprague@gmail.com", text: "devfestprague@gmail.com"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: false

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Jak se na něj dostat?"
findWayDistance: "Vzdálenost"
findWayDriving: "Autem"
findWayWalking: "Pěšky"
findWayTransit: "Hromadnou dopravou"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
yourLocationPlaceholder: "Odkud pojedete?"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Pohyb po Praze"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards: 
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   - 
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

randomSpeakersButtonText: "Zobrazit všechny speakery na DevFestu"

# GeekFun
aboutGeekfunTitle: "Let's geek out!"
geekfunRows:
 - {
  title: "",
  image: "geekfun-0.jpg",
  details: "DevFest je složen ze slov developers + festival. A o festivalovou část nepřijdete ani tento rok. Na obrázku vidíte atrium Fakulty Stavební, které se promění doslova v džungli geekovské zábavy. Bude si moci vyzkoušet spoustu starých i nových gadgetů – Googlích i neGooglích. Připravujeme zajímavé kombinace a propojení gadgetů, které jste ještě neviděli. Konkrétní gadgety nebudeme prozrazovat, ať se máte na co těšit. Vše bude formou hry, zapojíme určitě i naše partnery. Takže pokud zrovna nebudete na přednášce, nudit se určitě nebudete a snadno tak potkáte ostatní vývojáře a geeky. Jistě si pamatujete naše divadelní představení na keynote z <a href='http://www.youtube.com/watch?v=pwJk8JpYitw'>předminulého</a> a <a href='http://www.youtube.com/watch?v=wg-gOE8yxro'>minulého</a> roku. Tento rok na keynote nic nebude. We promise ;-<a href='https://www.youtube.com/watch?v=MefZfhxgpZE'>)</a>"
   }

# BusinessBuild
aboutBusinessbuildTitle: "Budujeme ... business!"
businessbuildRows:
 - {
  title: "Budovat, realizovat, monetizovat",
  image: "geekfun-0.jpg",
  details: "Na letošním DevFestu se nenaučíte budovat jenom software a hardware. Naučíte se také vybudovat svojí vlastní firmu, realizovat nápady, vést projekty a monetizovat aplikace.<br><br>Připravili jsme pro vás pestrý program, který by vám měl poskytnout dostatek informací k tomu, abyste třeba následující den vyrazili a započali epickou cestu k vlastnímu startupu. Můžete se těšit na spoustu skvělých přednášek a jeden speciální workshop."
   }
 - {
  title: "Přednášky",
  image: "geekfun-0.jpg",
  details: "Připravte se na pořádnou dávku informací a motivace od známých podnikatelů, vývojařů a projektových manažerů, kteří se s vámi podělí o své zkušenosti. A komu to nebude stačit, tak ten může po přednáškách rovnou zamířit na workshop, kde budou někteří z přednášejících vystupovat v roli mentorů."
   }
 - {
  title: "Workshop",
  image: "geekfun-0.jpg",
  details: "Máte nějaký nápad, který byste chtěli realizovat? Chcete vybudovat vlastní start-up, monetizovat svojí aplikaci, nebo už jste na půli cesty a jen se chcete zeptat na radu? <br><br> Pokud ano, tak přesně pro vás je určen náš workshop, na kterém vám zkušení mentoři odpoví na vaše otázky, poradí vám, čeho se vyvarovat a pomohou vám vytvořit plán, který bude moci sloužit jako odrazový můstek na cestě k vašemu cíli."
   }

# MachineRoom
aboutMachineroomTitle: "Stroje, jež jsme vybudovali...<br>...ožívají na DevFestu!"
machineroomSpeakersTitle: "Přednášející v MachineRoom"
machineroomRows:
 - {
  title: "Poznáte, co skrývá Open Hardware",
  image: "machineroom-0.png",
  details: "MachineRoom vám odhalí tajemství droboučkých přístrojů, z nichž mnohé si můžete sami postavit v kanceláři nebo doma – zkrátka na místě blízkém svému srdci. V MachineRoom a na souvisejících přednáškách budete mít možnost poznat, jak na to."
   }
 - {
  title: "Dotýkejte se a interagujte",
  image: "machineroom-3.jpg",
  details: "MachineRoom nebude statickou galerií, ani výstavou. Exponáty budou živé a s mnohými bude možné interagovat. Už nyní se na vaši společnost těší."
   }
 - {
  title: "Ukážeme vám, jak začít, jak se vyznat a jak se propojit",
  image: "machineroom-2.jpg",
  details: "MachineRoom na DevFestu bude jedním z míst s největší koncentrací zájemců o Open Hardware a Robotiku v Praze. Budete si moci prohlédnout, co všechno Open Hardware nabízí, a přítomní rádi poradí, kde co sehnat a s čím začít. Je libo Arduino, RaspberryPi, či BeagleBone? A propojením teplotních senzorů nebo robota s vaším Android zařízením to teprve začíná..."
   }
machineroomTechnologies:
 - {title: "Arduino", image: "tech-arduino.png"}
 - {title: "RaspberryPI", image: "tech-raspberrypi.png"}
 - {title: "BeagleBone", image: "tech-beaglebone.png"}
 - {title: "PICAXE", image: "tech-picaxe.png"}
 - {title: "Artoo.io", image: "tech-artooio.png"}
 - {title: "Ruby", image: "tech-ruby.png"}
 - {title: "Swift", image: "tech-swift.jpg"}
 - {title: "Android", image: "tech-android.png"}
 - {title: "Android Wear", image: "tech-wear.jpg"}